In [2]:
# libraries importing 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder # for handling categorical data
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error # for model evaluation

In [3]:
# data loading 
df=pd.read_csv(r"C:\Users\INDIAN\Downloads\AI_projects\car_price_predictor\data\cardekho.csv")
df.head()

                           name  year  selling_price  km_driven  ... mileage(km/ltr/kg)  engine max_power seats
0        Maruti Swift Dzire VDI  2014         450000     145500  ...              23.40  1248.0        74   5.0
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  ...              21.14  1498.0    103.52   5.0
2      Honda City 2017-2020 EXi  2006         158000     140000  ...              17.70  1497.0        78   5.0
3     Hyundai i20 Sportz Diesel  2010         225000     127000  ...              23.00  1396.0        90   5.0
4        Maruti Swift VXI BSIII  2007         130000     120000  ...              16.10  1298.0      88.2   5.0

[5 rows x 12 columns]

In [4]:
# drop un wanted columns

df.drop(columns=["name","max_power"],inplace=True)

In [5]:
df.head()

   year  selling_price  km_driven    fuel seller_type transmission         owner  mileage(km/ltr/kg)  engine  seats
0  2014         450000     145500  Diesel  Individual       Manual   First Owner               23.40  1248.0    5.0
1  2014         370000     120000  Diesel  Individual       Manual  Second Owner               21.14  1498.0    5.0
2  2006         158000     140000  Petrol  Individual       Manual   Third Owner               17.70  1497.0    5.0
3  2010         225000     127000  Diesel  Individual       Manual   First Owner               23.00  1396.0    5.0
4  2007         130000     120000  Petrol  Individual       Manual   First Owner               16.10  1298.0    5.0

In [6]:
# rename mileage(km/ltr/kg) to mileage
df.rename(columns={"mileage(km/ltr/kg)":"mileage"},inplace=True)

In [23]:
# filling null values ''
df["mileage"]=df["mileage"].fillna(df["mileage"].mean())
df["engine"]=df["engine"].fillna(df["engine"].mean())
df["seats"]=df["seats"].fillna(df["seats"].mean())

In [24]:
# encoding categorical columns
label=LabelEncoder()  # initialize label encoder 

df["enoded_fuel"]=label.fit_transform(df["fuel"])
var=dict(zip(df["fuel"],df["enoded_fuel"]))
print(var)

# encoding seler type
df["encoded_seller"]=label.fit_transform(df["seller_type"])
var1=dict(zip(df["seller_type"],df["encoded_seller"]))
print(var1)

# encoding transmission ciolumn
df["encoded_trans"]=label.fit_transform(df["transmission"])
var2=dict(zip(df["transmission"],df["encoded_trans"]))
print(var2)

# encodeing owner column
df["encoded_owner"]=label.fit_transform(df["owner"])
var3=dict(zip(df["owner"],df["encoded_owner"]))
print(var3)

{'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}
{'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}
{'Manual': 1, 'Automatic': 0}
{'First Owner': 0, 'Second Owner': 2, 'Third Owner': 4, 'Fourth & Above Owner': 1, 'Test Drive Car': 3}

In [26]:
df.isnull().sum()

year              0
selling_price     0
km_driven         0
fuel              0
seller_type       0
transmission      0
owner             0
mileage           0
engine            0
seats             0
enoded_fuel       0
encoded_seller    0
encoded_trans     0
encoded_owner     0
dtype: int64

In [27]:
# feature selection
x=df.drop(columns=["selling_price","fuel","seller_type","transmission","owner"])
y=df["selling_price"]

In [28]:
x.isnull().sum(),y.isnull().sum()

(year              0
 km_driven         0
 mileage           0
 engine            0
 seats             0
 enoded_fuel       0
 encoded_seller    0
 encoded_trans     0
 encoded_owner     0
 dtype: int64,
 np.int64(0))

In [29]:
# splitting data 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
# model selection 
model=LinearRegression()

# model training
model.fit(x_train,y_train)

LinearRegression()

In [36]:
# test model on test data
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)

0.5946189250170264

In [37]:
# accuracy on train data 
y_pred2=model.predict(x_train)
r2_score(y_train,y_pred2)

0.5812678349247643